spring:
  application:
    name: ASE-UserService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.sau-portal.de/realms/sau
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:file:./data/mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: always



  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /api/antrag
