-- Insert semester data with separate INSERT statements
INSERT INTO SEMESTERS (SEMESTER_CODE, SEMESTER_NAME, SEMESTER_START, SEMESTER_END, SEMESTER_TYPE, SEMESTER_YEAR, DEGREE)
VALUES ('2025S', 'Summer Semester 2025', '2025-06-10', '2025-11-24', 'SUMMER', 2025, 'BACHELOR');

INSERT INTO SEMESTERS (SEMESTER_CODE, SEMESTER_NAME, SEMESTER_START, SEMESTER_END, SEMESTER_TYPE, SEMESTER_YEAR, DEGREE)
VALUES ('2025W', 'Winter Semester 2025/2026', '2025-10-01', '2026-03-31', 'WINTER', 2025, 'BACHELOR');

-- Insert user data with semester reference
-- INSERT INTO USERS (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, MATRICULATION_NUMBER, STUDY_PROGRAM, DEGREE, CURRENT_SEMESTER, STANDARD_STUDY_DURATION, STUDY_START_SEMESTER, STUDY_END_SEMESTER, UNIVERSITY_SEMESTER, LEAVE_OF_ABSENCE_SEMESTERS, EMAIL, SEMESTER_ID)
-- VALUES ('Test', 'Test', '1990-01-01', '123456', 'INFORMATIK', 'BACHELOR', 1, 6, '2023-10-01', '2026-09-30', 1, 0, 'test-receive@arnold-of.de', 1);

-- Insert dozenten data
INSERT INTO DOZENTEN (ID, FIRST_NAME, LAST_NAME, TITLE, EMAIL, EMPLOYEE_NUMBER, DEPARTMENT, OFFICE_NUMBER, USERNAME, DATE_OF_BIRTH, ADDRESS, PHONE_NUMBER, WORKING_TIME_MODEL, FIELD_CHAIR, EMPLOYMENT_STATUS)
VALUES ('DOZ001', 'Hans', 'Müller', 'Prof. Dr.', 'hans.mueller@university.de', 'EMP001', 'Computer Science', 'A101', 'hmueller', '1970-05-15', 'University St. 1, 12345 City', '+49-123-456-7890', 'Full-time', 'Software Engineering', 'Tenured');

INSERT INTO DOZENTEN (ID, FIRST_NAME, LAST_NAME, TITLE, EMAIL, EMPLOYEE_NUMBER, DEPARTMENT, OFFICE_NUMBER, USERNAME, DATE_OF_BIRTH, ADDRESS, PHONE_NUMBER, WORKING_TIME_MODEL, FIELD_CHAIR, EMPLOYMENT_STATUS)
VALUES ('DOZ002', 'Anna', 'Schmidt', 'Dr.', 'anna.schmidt@university.de', 'EMP002', 'Computer Science', 'A102', 'aschmidt', '1975-08-22', 'University St. 2, 12345 City', '+49-123-456-7891', 'Full-time', 'Database Systems', 'Permanent');

INSERT INTO DOZENTEN (ID, FIRST_NAME, LAST_NAME, TITLE, EMAIL, EMPLOYEE_NUMBER, DEPARTMENT, OFFICE_NUMBER, USERNAME, DATE_OF_BIRTH, ADDRESS, PHONE_NUMBER, WORKING_TIME_MODEL, FIELD_CHAIR, EMPLOYMENT_STATUS)
VALUES ('DOZ003', 'Thomas', 'Weber', 'Prof. Dr.', 'thomas.weber@university.de', 'EMP003', 'Computer Science', 'A103', 'tweber', '1968-03-10', 'University St. 3, 12345 City', '+49-123-456-7892', 'Full-time', 'Algorithms', 'Tenured');
