apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: antrag-service

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  environment: ase-6
  managed-by: kustomize
  app: antrag-service

namePrefix: "ase-"

namespace: ase-6

replicas:
  - name: antrag-service
    count: 1
