apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-cm
data:
  SMTP_SERVER_HOSTNAME: "mail.your-server.de"
  SMTP_SERVER_PORT: "587"
  SMTP_SENDER_ADDRESS: "test-send@arnold-of.de"
  SMTP_SENDER_NAME: "Hochschulverwaltungssystem"

