name: Test Build Workflow

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build and push image
        uses: Agile-Software-Engineering-25/build-and-publish-image@v1
        with:
          image_name: "team-06-backend-antrag-service"
          push: false

