name: Deploy Workflow

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Build and push image
        uses: Agile-Software-Engineering-25/build-and-publish-image@v1
        with:
          image_name: "team-06-backend-antrag-service"
          push: true

      - name: Deploy to k8s
        uses: Agile-Software-Engineering-25/deploy-to-k8s@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ vars.K8S_NAMESPACE }}
          tag: ${{ steps.vars.outputs.tag }}
          deployment: "ase-antrag-service"
